/*
 * This file is generated by jOOQ.
 */
package com.helloxin;


import com.helloxin.tables.Lottery;
import com.helloxin.tables.Movie;
import com.helloxin.tables.User;
import com.helloxin.tables.records.LotteryRecord;
import com.helloxin.tables.records.MovieRecord;
import com.helloxin.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>zootopia</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LotteryRecord, UInteger> IDENTITY_LOTTERY = Identities0.IDENTITY_LOTTERY;
    public static final Identity<MovieRecord, UInteger> IDENTITY_MOVIE = Identities0.IDENTITY_MOVIE;
    public static final Identity<UserRecord, UInteger> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LotteryRecord> KEY_LOTTERY_PRIMARY = UniqueKeys0.KEY_LOTTERY_PRIMARY;
    public static final UniqueKey<MovieRecord> KEY_MOVIE_PRIMARY = UniqueKeys0.KEY_MOVIE_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_USER_ID_INDEX = UniqueKeys0.KEY_USER_USER_ID_INDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<LotteryRecord, UInteger> IDENTITY_LOTTERY = Internal.createIdentity(Lottery.LOTTERY, Lottery.LOTTERY.ID);
        public static Identity<MovieRecord, UInteger> IDENTITY_MOVIE = Internal.createIdentity(Movie.MOVIE, Movie.MOVIE.ID);
        public static Identity<UserRecord, UInteger> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<LotteryRecord> KEY_LOTTERY_PRIMARY = Internal.createUniqueKey(Lottery.LOTTERY, "KEY_lottery_PRIMARY", Lottery.LOTTERY.ID);
        public static final UniqueKey<MovieRecord> KEY_MOVIE_PRIMARY = Internal.createUniqueKey(Movie.MOVIE, "KEY_movie_PRIMARY", Movie.MOVIE.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<UserRecord> KEY_USER_USER_ID_INDEX = Internal.createUniqueKey(User.USER, "KEY_user_user_id_index", User.USER.USER_ID);
    }
}
