/*
 * This file is generated by jOOQ.
 */
package com.helloxin;


import com.helloxin.tables.Lottery;
import com.helloxin.tables.Movie;
import com.helloxin.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Zootopia extends SchemaImpl {

    private static final long serialVersionUID = -1649953674;

    /**
     * The reference instance of <code>zootopia</code>
     */
    public static final Zootopia ZOOTOPIA = new Zootopia();

    /**
     * The table <code>zootopia.lottery</code>.
     */
    public final Lottery LOTTERY = com.helloxin.tables.Lottery.LOTTERY;

    /**
     * The table <code>zootopia.movie</code>.
     */
    public final Movie MOVIE = com.helloxin.tables.Movie.MOVIE;

    /**
     * The table <code>zootopia.user</code>.
     */
    public final User USER = com.helloxin.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Zootopia() {
        super("zootopia", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Lottery.LOTTERY,
            Movie.MOVIE,
            User.USER);
    }
}
