/*
 * This file is generated by jOOQ.
 */
package com.helloxin.tables.records;


import com.helloxin.tables.Lottery;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LotteryRecord extends UpdatableRecordImpl<LotteryRecord> implements Record6<UInteger, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2136635193;

    /**
     * Setter for <code>zootopia.lottery.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>zootopia.lottery.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>zootopia.lottery.user_id</code>. 中奖人id
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zootopia.lottery.user_id</code>. 中奖人id
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zootopia.lottery.user_name</code>. 中奖人名称
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zootopia.lottery.user_name</code>. 中奖人名称
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zootopia.lottery.lottery_game</code>. 抽奖场次
     */
    public void setLotteryGame(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>zootopia.lottery.lottery_game</code>. 抽奖场次
     */
    public String getLotteryGame() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zootopia.lottery.date_create</code>.
     */
    public void setDateCreate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>zootopia.lottery.date_create</code>.
     */
    public Timestamp getDateCreate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>zootopia.lottery.date_update</code>.
     */
    public void setDateUpdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>zootopia.lottery.date_update</code>.
     */
    public Timestamp getDateUpdate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Lottery.LOTTERY.ID;
    }

    @Override
    public Field<String> field2() {
        return Lottery.LOTTERY.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Lottery.LOTTERY.USER_NAME;
    }

    @Override
    public Field<String> field4() {
        return Lottery.LOTTERY.LOTTERY_GAME;
    }

    @Override
    public Field<Timestamp> field5() {
        return Lottery.LOTTERY.DATE_CREATE;
    }

    @Override
    public Field<Timestamp> field6() {
        return Lottery.LOTTERY.DATE_UPDATE;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public String component4() {
        return getLotteryGame();
    }

    @Override
    public Timestamp component5() {
        return getDateCreate();
    }

    @Override
    public Timestamp component6() {
        return getDateUpdate();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public String value4() {
        return getLotteryGame();
    }

    @Override
    public Timestamp value5() {
        return getDateCreate();
    }

    @Override
    public Timestamp value6() {
        return getDateUpdate();
    }

    @Override
    public LotteryRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public LotteryRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public LotteryRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public LotteryRecord value4(String value) {
        setLotteryGame(value);
        return this;
    }

    @Override
    public LotteryRecord value5(Timestamp value) {
        setDateCreate(value);
        return this;
    }

    @Override
    public LotteryRecord value6(Timestamp value) {
        setDateUpdate(value);
        return this;
    }

    @Override
    public LotteryRecord values(UInteger value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LotteryRecord
     */
    public LotteryRecord() {
        super(Lottery.LOTTERY);
    }

    /**
     * Create a detached, initialised LotteryRecord
     */
    public LotteryRecord(UInteger id, String userId, String userName, String lotteryGame, Timestamp dateCreate, Timestamp dateUpdate) {
        super(Lottery.LOTTERY);

        set(0, id);
        set(1, userId);
        set(2, userName);
        set(3, lotteryGame);
        set(4, dateCreate);
        set(5, dateUpdate);
    }
}
